winit-26 as default
imgui-rs/imgui-rs pull request #590
Opened 2021-12-26 20:54 UTC by sanbox-irl

This resolves #587

2021-12-27 12:25 UTC, dbr requested changes

2021-12-27 12:25 UTC, dbr commented on imgui-winit-support/src/lib.rs
> +    let winits_enabled = cfg(feature = "winit-26") as usize
```suggestion
    let winits_enabled = cfg!(feature = "winit-26") as usize
```

2022-01-06 06:49 UTC, HactarCE commented
I really appreciate the timely updates! Unfortunately, even though imgui-winit-support can use winit 0.26, imgui-rs is still stuck on glium 0.30 which requires glutin 0.27 which requires winit 0.25. glium 0.31 would work, though.

2022-02-21 23:02 UTC, sanbox-irl commented
I'm not sure what happened to the Git history here, but somehow it's completely messed up on my machine.

I'm going to close this PR and open another to merge

2022-02-21 23:02 UTC, closed without merging