Add functions `begin_popup_context_*`.
imgui-rs/imgui-rs pull request #738
Opened 2023-07-23 11:39 UTC by rodrigorc

Hi!

In ImGui there are these handy functions to do pop-up menus, usually by right-clicking the mouse. This PR adds basic wrappers around these.

The code is quite self-explanatory. The most notable thing missing is the ability to specify a flag other than `ImGuiPopupFlags_MouseButtonRight`. For me, I only open pop-ups when doing a `MouseButtonRight`, so this is good enough. But if you think it is wort it, we could ad an enum wrapper and a way to specify it, maybe a builder helper struct o a few `begin_popup_context_*_with_flags()` functions.

2023-09-15 03:14 UTC, sanbox-irl commented
Hey, thanks for this PR! This looks great -- I'll take a deeper look soon and likely merge!

2023-09-17 20:41 UTC, sanbox-irl requested changes
Took a look -- I think yup, your instinct is correct -- we'll need a version that can take an optional mouse button.

I'll push a version and let me know how it looks?

2023-09-17 21:22 UTC, sanbox-irl commented
okay @rodrigorc I added a few extra methods to handle setting a label or not. I agree that handling the non-RMB case should be deferred till we have a user who wants that, since it sounds...awfully niche and annoying.

Let me know what you think of these additions and we can merge it!

2023-09-20 18:10 UTC, rodrigorc commented
I see the changes all fine, thanks.

2023-09-23 22:34 UTC, merged